### ISSUE TITLE
Stack unable to delete app service plan

### ISSUE THREAD

**Issue by ksstott** [Azure/deployment-stacks#159] opened 2024-03-11 12:26 UTC
**Describe the bug**
When deploying a deployment stack with the `--delete-resources` flag and it attempts to delete an app service plan `Microsoft.Web/serverfarms` it fails with the following error:
```
{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'northeurope' and API version '2023-12-01' for type 'serverFarms'. The supported api-versions are '2023-12-01, 2023-01-01, 2022-09-01, 2022-03-01, 2021-03-01, 2021-02-01, 2021-01-15, 2021-01-01, 2020-12-01, 2020-10-01, 2020-09-01, 2020-06-01, 2019-08-01, 2018-11-01, 2018-02-01, 2017-08-01, 2016-09-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2014-11-01, 2014-06-01, 2014-04-01, 2014-04-01-preview, 2018-12-01-alpha'. The supported locations are 'msftwestus, msfteastus, msfteastasia, msftnortheurope, eastus2stage, centralusstage, southcentralus, southafricanorth, westus, australiaeast, brazilsouth, southeastasia, centralus, japanwest, centralindia, uksouth, canadaeast, koreacentral, francecentral, westus2, eastus, westindia, eastus2, australiacentral, germanywestcentral, norwayeast, uaenorth, swedencentral, qatarcentral, switzerlandnorth, northcentralus, ukwest, australiasoutheast, koreasouth, canadacentral, westeurope, southindia, westcentralus, westus3, eastasia, japaneast, jioindiawest, polandcentral, italynorth, israelcentral, northeurope'."}
```

**To Reproduce**
1. Create and deploy a deployment stack containing a `Microsoft.Web/serverfarms` 
2. Remove the  `Microsoft.Web/serverfarms` and redeploy the deployment stack with the `--delete-resources` flag 

**Expected behavior**
The deployment stack deploys successfully and the app service plan is deleted

**Server Debugging Information**
Correlation ID: 70bbf362-22db-4181-8277-e41f6f8e2666
Tenant ID: 
b958889c-3b36-45ec-ab56-b88c1a427797
Timestamp of issue (please include time zone): 11 Mar 2024, 10:37 UTC

**Comment by snarkywolverine** [comment] 2024-03-12 17:50
Hi @ksstott!  Thanks for reporting this.

It looks like the issue is related to a new api-version of Microsoft.Web - this should be resolved around 2100 UTC today (~4 hours from now).  After that, can you try again and let us know if it repros?

Meanwhile, we will investigate ways to prevent this from happening again.

**Comment by ksstott** [comment] 2024-03-19 11:47
> Hi @ksstott! Thanks for reporting this.
> 
> It looks like the issue is related to a new api-version of Microsoft.Web - this should be resolved around 2100 UTC today (~4 hours from now). After that, can you try again and let us know if it repros?
> 
> Meanwhile, we will investigate ways to prevent this from happening again.

Hi @snarkywolverine, thanks for getting back to me on this. 

I've retried today and it worked as expected. Do you need this issue kept open while you continue your investigation on ways to prevent this happening again?

**Comment by snarkywolverine** [comment] 2024-03-19 18:43
I'll go ahead and close the issue. We have a partner team that is already making changes for this scenario. Glad to hear that worked!

**Closed as completed by snarkywolverine** 2024-03-19 18:43 UTC
Labels: bug
