### ISSUE TITLE
Align error reporting behavior between Deployment and DeploymentStack cmdlets

### ISSUE THREAD

**Issue by alex-frankel** [Azure/deployment-stacks#11] opened 2021-10-21 16:10 UTC
Got a preflight error with the deployment. The top level error is not helpful, nor is showing the full JSON error response:

Initial error:
```
Error             : DeploymentFailed - At least one resource deployment operation failed. Please list deployment operations for details.     
                    Please see https://aka.ms/DeployOperations for usage details.
```

Output of `$stack.error | ConvertTo-Json -Depth 50`:

```json
{
  "Code": "DeploymentStackUpdateFailed",
  "Message": "One or more stages of deploymentStack update failed.",
  "Target": null,
  "Details": [
    {
      "Code": "DeploymentStackDeploymentFailed",
      "Message": "One or more resources could not be deployed.",
      "Target": null,
      "Details": [
        {
          "Code": "DeploymentFailed",
          "Message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
          "Target": null,
          "Details": [
            {
              "Code": "DeploymentFailed",
              "Message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
              "Target": null,
              "Details": null,
              "AdditionalInfo": null
            },
            {
              "Code": "DeploymentFailed",
              "Message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
              "Target": null,
              "Details": null,
              "AdditionalInfo": null
            }
          ],
          "AdditionalInfo": null
        }
      ],
      "AdditionalInfo": null
    }
  ],
  "AdditionalInfo": null
}
```

I ended up figuring out by doing a standard deployment, which gives me the following output by default:

```
New-AzDeployment: 11:06:21 AM - The deployment 'main' failed with error(s). Showing 2 out of 2 error(s).
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
 - {
  "Code": "Conflict",
  "Message": "Website with given name plainsite already exists.",
  "Target": null,
  "Details": [
    {
      "Message": "Website with given name plainsite already exists."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "54001",
        "MessageTemplate": "Website with given name {0} already exists.",
        "Parameters": [
          "plainsite"
        ],
        "Code": "Conflict",
        "Message": "Website with given name plainsite already exists."
      }
    }
  ],
  "Innererror": null
} (Code:Conflict)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details. (Code: DeploymentFailed)
 - {
  "Code": "Conflict",
  "Message": "Website with given name fancysite already exists.",
  "Target": null,
  "Details": [
    {
      "Message": "Website with given name fancysite already exists."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "54001",
        "MessageTemplate": "Website with given name {0} already exists.",
        "Parameters": [
          "fancysite"
        ],
        "Code": "Conflict",
        "Message": "Website with given name fancysite already exists."
      }
    }
  ],
  "Innererror": null
} (Code:Conflict)
CorrelationId: 85db1c40-f65d-4a9b-bae7-a451683e0468
```

I would have expected to get the same info in both contexts.

**Comment by TSunny007** [comment] 2021-10-26 19:43
This currently happens by design. A deploymentStack does not contain "failed resources". The fix for this is one of the following:
1) Generate a Snapshot when a deployment goes through
2) Populate FailedResources right on the deploymentStack

**Comment by ouldsid** [comment] 2021-10-26 19:46
@TarunSunkaraneni let's follow up on this in our snapshot discussion : We do have an active PR that is trying to resolve this issue but we need to discuss this in snapshot discuttion DEVOPS PR  5235697

**Comment by aperezmicrosoft** [comment] 2023-03-06 21:43
In the latest release, we no output the entire error entity

**Closed as completed by aperezmicrosoft** 2023-03-06 21:43 UTC
Labels: bug
