### ISSUE TITLE
Deployment Stacks should support tags

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#30] opened 2021-11-02 11:34 UTC
**Is your feature request related to a problem? Please describe.**
Deployment stacks should support tags so you can add some metadata that might be useful when you browse stacks. It might be very useful when you view multiple stacks across multiple subscriptions. Deployments already support tags.

**Describe the solution you'd like**
It is clear

**Describe alternatives you've considered**
no alternatives

**Comment by bmoore-msft** [comment] 2021-11-02 19:15
They should... out of curiosity - how will you use them?

**Comment by slavizh** [comment] 2021-11-03 08:53
I guess mainly in portal to may be track things like:
- team/department who owns the stack
- to which application the stack belongs
- etc.
Basically the same things you use tags for other resources excluding billing if Stacks is free.

**Comment by dantedallag** [comment] 2023-03-03 01:17
Marking this as a duplicate of https://github.com/Azure/deployment-stacks/issues/86. Will close both when the other is resolved.

**Closed as completed** 2023-03-06 18:46 UTC
Labels: bug
