### ISSUE TITLE
can't delete the resource because it was locked

### ISSUE THREAD

**Issue by slavizh** [Azure/deployment-stacks#26] opened 2021-11-01 10:01 UTC
Resource cannot be deleted if there is a lock. Reference #24

**Comment by alex-frankel** [comment] 2021-11-02 16:38
Was the lock itself deployed with the stack? What is the expected behavior?

**Comment by slavizh** [comment] 2021-11-03 08:39
It was not deployed trough the stack. The lock was deployed by Azure SQL Monitoring solution from portal - basically a views resource type that had lock.

**Comment by bmoore-msft** [comment] 2021-11-05 21:32
@slavizh - so the lock was explicitly applied via portal?  Or via another resource in the template for the stack?

**Comment by slavizh** [comment] 2021-11-08 12:42
@bmoore-msft applied via portal when Azure SQL Monitoring solution was deployed so outside of the stack deployment which does not define that resource at all.

**Comment by bmoore-msft** [comment] 2021-11-08 20:25
Ok, so I think this one we should respect... if the resource is locked (outside of the stack) the stack should respect that lock, otherwise the platform is a little suspect in this area.

Is the lock (that's applied by SQL Monitoring) visible in portal?  (they aren't doing something funky with it)

**Comment by slavizh** [comment] 2021-11-09 07:16
regular lock 

![image](https://user-images.githubusercontent.com/11890856/140878952-d6f7c8e9-10a3-4886-a475-6ecbc2412a3b.png)

**Comment by snarkywolverine** [comment] 2021-11-09 18:54
I agree that, if the stack is managing a resource that is locked outside the scope of the stack, then the purge should fail (which sounds like what happened here).

I recognize that, in this case, the scenario is a little convoluted (since the resource shouldn't have been managed in the first place, see issue #24) - but the locking behavior is correct.  I'm going to close this -- feel free to reactivate if you have further questions.

**Closed as completed by snarkywolverine** 2021-11-09 18:54 UTC

**Comment by slavizh** [comment] 2021-11-10 07:19
@snarkywolverine no problem. I have opened the issue because I was asked. For me the behavior of not being able to delete locked resource that is not part of the managed resources is correct as well.
